### ISSUE TITLE
Understanding configuration terms

### ISSUE THREAD

**Issue by Yash685** [AiX-im/Sample-based-GNN#1]
UP_DEGREE:1
PIPELINE_NUM:4
CACHE_RATE:0.10
CACHE:1
FEATURE_CACHE_RATE:0.1
PROC_OVERLAP:0
PROC_LOCAL:0
PROC_CUDA:0
PROC_REP:0
PUSHDOWN:0
LOCK_FREE:1

Can you explain to me what these flags mean when specifying in cfg file?
Also what are differences between GS_SAMPLE_ALL_GPU, GS_SAMPLE_PDCACHE, GS_SAMPLE_CACHE?

**Comment by AiX-im** [comment]
Thank you for your issue. "PIPELINE_NUM" represents the number of batches contained in each super-batch in super-batch pipelining. "CACHE_RATE" represents the proportion of hot vertices computed by the CPU to all vertices in the initial state. "CACHE" indicates whether GPU memory caching of vertex features is used, and "FEATURE_CACHE_RATE" represents the number of vertex features cached by the GPU in the initial state. All other parameters have been deprecated. 

Regarding the algorithm differences, "GS_SAMPLE_ALL_GPU" utilizes GPU exclusively for the sampling-gathering-training process, "GS_SAMPLE_PDCACHE" offloads hot vertices computations to the CPU, and "GS_SAMPLE_CACHE" is a backup code.

I apologize for the inconvenience caused, and I will add parameter explanations in future code updates and strive to remove redundant code and deprecated parameters.
